name: Manual trigger
on:
   workflow_dispatch:
   
jobs:
  Manual:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3    
      - name: Run HoneygainPot
        run: python main.py
        env:
         MAIL_JWD: ${{ secrets.MAIL_JWD }}
         PASS_JWD: ${{ secrets.PASS_JWD }}
         IsGit: 1
